version: '3.1'

services:
  mongo:
    image: mongo:4.4.5
    command: --bind_ip 0.0.0.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - 27018:27017
    volumes:
      - dbdata:/data/db
      - configdbdata:/data/configdb

  mongo-express:
    image: mongo-express:0.54
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongo

  # discord:
  #   image: python:3.9
  #   volumes:
  #     - .:/app
  #     - python-packages:/usr/local/lib/python3.9/site-packages
  #   working_dir: /app
  #   command: /bin/bash -c "pip install -r requirements.txt && python main.py"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mongo

volumes:
  dbdata:
  configdbdata:
  # python-packages:
